name: Build and Delivery

on:
  workflow_run:
    workflows: ["Test Python App"]
    branches: [main]
    types: [completed]

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}  # Используем переменную (vars.)
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Используем секрет (secrets.)

      - name: Build and push
        uses: docker/build-push-action@v6  # Версия v6 как в ТЗ
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest  # Полный тегs